### ISSUE TITLE
Status bar message stuck on "Starting" after restarting RLS

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rls-vscode#283]
If RLS crashes and I restart it, the status message gets stuck with a spinner at "Starting", even though RLS seems to boot up and work fine.

**Comment by nrc** [comment]
Should be fixed now.

**Comment by fpcsong** [comment]
I have this bug too,  

> rls-preview 0.130.5-nightly (e67fd48 2018-08-24)

> rustc 1.30.0-nightly (39e6ba821 2018-08-25)

**Comment by nrc** [comment]
@fpcsong could you try running `rustup update` today and see if you still have the problem please?

**Comment by fpcsong** [comment]
I run rustup update and restart the vscode, still have this problem, I reinstall the rls but nothing changed. 
I work on toolchain nightly.

**Comment by fpcsong** [comment]
well, after I disable another Rust extension Rust, "starting" disappeared

**Comment by quamis** [comment]
> well, after I disable another Rust extension Rust, "starting" disappeared

That was it. I had both "Rust (rls)" and "Rust" installed. I disabled "Rust" now.
