### ISSUE TITLE
Double docs and type on hover

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rls-vscode#343]
If you hover over an ident, then sometimes you get double the info you should. This doesn't happen all the time, and restarting fixes this. I don't know what triggers it, but I've seen it a few times on master, I assume something to do with VSCode workspaces. There are not multiple RLS processes being started.

**Comment by jaredready** [comment]
Seeing the same here. They're getting duplicated in the Problems panel as well.

<img width="1440" alt="screen shot 2018-07-27 at 9 48 28 pm" src="https://user-images.githubusercontent.com/3362733/43352272-f3e3dd60-91e6-11e8-89cb-5e18bccf2f04.png">

**Extensions:**
```
Pendrica.chef-0.7.0
alefragnani.bookmarks-9.0.2
castwide.solargraph-0.17.6
daylerees.rainglow-1.5.2
eamodio.gitlens-8.5.3
equinusocio.vsc-material-theme-2.3.0
esbenp.prettier-vscode-1.5.0
kumar-harsh.graphql-for-vscode-1.12.0
mauve.terraform-1.2.3
mindginative.terraform-snippets-2.1.0
ms-kubernetes-tools.vscode-kubernetes-tools-0.1.11
ms-python.python-2018.7.1
ms-vsliveshare.vsliveshare-0.3.472
oderwat.indent-rainbow-7.2.2
peterjausovec.vscode-docker-0.1.0
pkief.material-icon-theme-3.5.2
pnp.polacode-0.2.2
pthorsson.vscode-jsp-0.0.2
rebornix.ruby-0.18.0
redhat.java-0.28.0
redhat.vscode-yaml-0.0.14
richie5um2.vscode-sort-json-1.13.0
rust-lang.rust-0.4.9
shan.code-settings-sync-3.0.0
vscjava.vscode-java-debug-0.10.0
vscjava.vscode-java-pack-0.3.0
vscjava.vscode-java-test-0.7.1
vscjava.vscode-maven-0.10.0
vscodevim.vim-0.15.7
wayou.vscode-todo-highlight-1.0.4
```

**Rustup version:**
```
rustup --version
rustup 1.13.0 (ea9259c1b 2018-07-16)
```

**RLS version:**
```
rls --version
rls-preview 0.127.0-stable (d2ade31 2018-05-08)
```

**VSCode 1.25.1
MacOS 10.13.6 (17G65)**

**Comment by nrc** [comment]
I think this is fixed by https://github.com/rust-lang-nursery/rls-vscode/commit/e7c5ee59d01f07351966ee2e4e29941065d35c99

**Comment by ralfbiedert** [comment]
Has this fix been published yet? I am not sure if this is still around, or around again.

![screen shot 2018-12-08 at 16 10 31](https://user-images.githubusercontent.com/301288/49687506-ffce8b80-fb03-11e8-9bf0-d079f10cd63b.png)

Using 0.5.2 and rls-preview 1.31.6 (cfd8449 2018-12-03).

**Comment by jens1o** [comment]
I'm seeing this too.

**Comment by suleyth** [comment]
Any fix yet? ;-;

**Comment by krlozadan** [comment]
Yeah.. this hasn't been fixed I'm still getting it. I'm using:
```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```
