### ISSUE TITLE
No tasks in VSC 1.25.0

### ISSUE THREAD

**Issue by Barugon** [rust-lang-nursery/rls-vscode#359]
The default tasks are no longer available after upgrading to VSC 1.25.0.

To duplicate, upgrade to VSC 1.25.0, click the Tasks menu, click the Run Task menu item item and note that the list is now empty.

**Comment by HyperHamster** [comment]
Issue confirmed with VSCode `1.25.0` on Arch Linux `x86_64`.

**Comment by agentsim** [comment]
Also happening with VSCode `1.25.0` on Fedora 28.

**Comment by hpesoj** [comment]
Confirmed on Windows 10 as well.

**Comment by TomMarius** [comment]
Could someone please share a template in the meantime until it's fixed?

**Comment by fj** [comment]
In the meantime, you can get the tasks by looking at the source; they're added here: https://github.com/rust-lang-nursery/rls-vscode/blob/master/src/tasks.ts#L88-L169

**Comment by nrc** [comment]
Fixed by #361

**Comment by fj** [comment]
Confirmed that this works for me. Thank you @nrc and @HyperHamster!

**Comment by nrc** [comment]
Released 0.4.7 with this fix

**Comment by Barugon** [comment]
Works for me, thanks.

**Comment by scautura** [comment]
I'm still having a few issues. I get the tasks showing up, but when I try to use one (doesn't matter which one), I get:
`> Executing task in folder ProjectFolder: cargo task <`
Followed by nothing (doesn't seem to run at all); where "task" is one of run, build, check, bench, clean, or test.
If I "Configure Tasks" and change `"type": "cargo",` to `"type": "shell",`, it runs as expected.

**Comment by liuz430524** [comment]
@TomMarius +1

**Comment by hpesoj** [comment]
If you try "Configure Task", the generated task has `"cargo"` in the `"type"` field. Apparently, this should be `"shell"` or `"process"`. Here is a fixed `tasks.json`:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "shell",
            "label": "cargo build",
            "command": "cargo",
            "args": [
                "build"
            ],
            "problemMatcher": [
                "$rustc"
            ],
            "group": "build"
        },
        {
            "type": "shell",
            "label": "cargo check",
            "command": "cargo",
            "args": [
                "check"
            ],
            "problemMatcher": [
                "$rustc"
            ],
            "group": "build"
        },
        {
            "type": "shell",
            "label": "cargo run",
            "command": "cargo",
            "args": [
                "run"
            ],
            "problemMatcher": [
                "$rustc"
            ],
        },
        {
            "type": "shell",
            "label": "cargo test",
            "command": "cargo",
            "args": [
                "test"
            ],
            "problemMatcher": [
                "$rustc"
            ],
            "group": "test"
        },
        {
            "type": "shell",
            "label": "cargo bench",
            "command": "cargo",
            "args": [
                "+nightly",
                "bench"
            ],
            "problemMatcher": [
                "$rustc"
            ],
            "group": "test"
        },
        {
            "type": "shell",
            "label": "cargo clean",
            "command": "cargo",
            "args": [
                "clean"
            ],
            "problemMatcher": []
        },
    ]
}
```

**Comment by nrc** [comment]
cc @matklad re the last comment. Would you expect changing the type to `cargo` to break things?

**Comment by matklad** [comment]
No, I think we must define a fresh type of tasks to make things work. I am not too sure about this, but, for example, cake defines the new type: 
https://github.com/Microsoft/vscode/issues/53673#issuecomment-402987914. 

I wonder what distinguish setups of people for whom type cargo does not work?

**Comment by matklad** [comment]
Reprodced, this is windows specific.

**Comment by matklad** [comment]
Ok, the actual fix is https://github.com/rust-lang-nursery/rls-vscode/pull/371 :)

**Comment by nrc** [comment]
Closed by #371
